name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Enable manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to update README
        run: python update_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "Update README Action"
          git add README.md
          git commit -m "Update README with latest blog posts"
          if [[ `git status --porcelain` ]]; then git add . && git commit -m "README.md updated by action" && git push; fi