name: Update README

on:
  schedule:
    - cron: '0 10 * * *' # Run daily at 10 AM
  workflow_dispatch: # Enable manual triggering
  push:
    branches:
      - main


jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to update README
        run: python update_readme.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "Update README Action"
          git add README.md
          git commit -m "Update README with latest blog posts"
          git remote set-url --push origin https://jigarkkarangiya:${GITHUB_TOKEN}@github.com/jigarkkarangiya/jigarkarangiya-blogs.git
        env:
          GITHUB_TOKEN: ${{ secrets.JKB_WF_TOKEN }}